### ISSUE TITLE
State checking is buggy

### ISSUE THREAD

**Issue by rumkin** [sosedoff/lxc-ruby#13]
LXC box state checking is buggy. My lxc version returns machine state in lower case, so all checks of `valid_state` fail.

```
LXC::Shell.valid_state?('stopped') # => false
```

**Comment by sosedoff** [comment]
What version of LXC are you running? Can you provide output of `lxc-info` here ?

**Comment by rumkin** [comment]
Checked again and it works as expected. So it's my fault.
P.S. Why doesn't method `wait` check if state arg is a valid state?
